# Generated by Django 3.2.9 on 2021-11-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('neither', 'Neither'), ('male', 'Male'), ('female', 'Female')], default='neither', max_length=7)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('github_link', models.URLField(blank=True, default='')),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
